import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export function exportTripPdf(
  trip: any,
  destinations: any[],
  activities: any[],
  expenses: any[],
  checklist: any[]
) {
  const doc = new jsPDF();
  

  const totalExpenses = expenses.reduce(
    (sum, e) => sum + Number(e.amount || 0),
    0
  );

  const remainingBudget = trip.budget - totalExpenses;

  doc.setFillColor(6, 78, 59);
  doc.rect(0, 0, 210, 35, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("Travel Planner Report", 14, 18);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(
    `Generated: ${new Date().toLocaleDateString()}`,
    14,
    28
  );

  doc.setTextColor(0, 0, 0);

  doc.setDrawColor(220);
  doc.roundedRect(14, 45, 180, 40, 3, 3);

  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text(trip.title, 20, 58);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");

  doc.text(
    `Budget: €${trip.budget}`,
    20,
    68
  );

  doc.text(
    `Dates: ${trip.startDate.substring(0, 10)} - ${trip.endDate.substring(0, 10)}`,
    20,
    76
  );

  let y = 95;

  autoTable(doc, {
    startY: y,

    head: [
      ["Destination", "Location", "Arrival", "Departure"]
    ],

    body: destinations.map((d) => [
      d.name,
      d.location ?? "-",
      d.startDate?.substring(0, 10) ?? "-",
      d.endDate?.substring(0, 10) ?? "-"
    ]),

    headStyles: {
      fillColor: [6, 78, 59],
      textColor: 255,
      fontStyle: "bold"
    },

    alternateRowStyles: {
      fillColor: [245, 245, 245]
    },

    styles: {
      fontSize: 9
    }
  });

  y = (doc as any).lastAutoTable.finalY + 10;

  autoTable(doc, {
    startY: y,

    head: [
      ["Activity", "Date", "Time", "Cost", "Status"]
    ],

    body: activities.map((a) => [
      a.name,
      a.date?.substring(0, 10) ?? "-",
      a.time ?? "-",
      a.estimatedCost
        ? `€${a.estimatedCost}`
        : "-",
      a.status ?? "-"
    ]),

    headStyles: {
      fillColor: [6, 78, 59],
      textColor: 255,
      fontStyle: "bold"
    },

    alternateRowStyles: {
      fillColor: [245, 245, 245]
    },

    styles: {
      fontSize: 9
    }
  });

  y = (doc as any).lastAutoTable.finalY + 10;

  autoTable(doc, {
    startY: y,

    head: [
      ["Expense", "Category", "Amount"]
    ],

    body: expenses.map((e) => [
      e.name,
      e.category,
      `€${e.amount}`
    ]),

    headStyles: {
      fillColor: [6, 78, 59],
      textColor: 255,
      fontStyle: "bold"
    },

    alternateRowStyles: {
      fillColor: [245, 245, 245]
    },

    styles: {
      fontSize: 9
    }
  });

  y = (doc as any).lastAutoTable.finalY + 10;

  autoTable(doc, {
    startY: y,

    head: [
      ["Checklist Item", "Completed"]
    ],

    body: checklist.map((c) => [
      c.name,
      c.isCompleted ? "Completed" : "Pending"
    ]),

    headStyles: {
      fillColor: [6, 78, 59],
      textColor: 255,
      fontStyle: "bold"
    },

    alternateRowStyles: {
      fillColor: [245, 245, 245]
    },

    styles: {
      fontSize: 9
    }
  });

  y = (doc as any).lastAutoTable.finalY + 15;

  const pageHeight = doc.internal.pageSize.height;

  if (y + 35 > pageHeight) {
    doc.addPage();
    y = 20;
  }

  doc.setFillColor(240, 253, 244);
  doc.roundedRect(14, y, 180, 28, 3, 3, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);

  doc.text(
    `Total Expenses: €${totalExpenses}`,
    20,
    y + 10
  );

  doc.text(
    `Remaining Budget: €${remainingBudget}`,
    20,
    y + 20
  );

  doc.setFontSize(8);
  doc.setTextColor(120);

  doc.text(
    "Generated by Travel Planner",
    14,
    pageHeight - 10
  );

  doc.save(
    `${trip.title.replace(/\s+/g, "-")}-report.pdf`
  );
}